// routes/index.js
import express from "express";
import AuthenticationRoutes from "./Authentication.js";
import BankDashboardRoutes from "./BankDashboard.js";
import FarmerProfileRoutes from "./FarmerProfile.js";
import FinancialHistoryRoutes from "./FinancialHistory.js";
import LoanRoutes from "./loan.js";
import TransactionRoutes from "./Transaction.js";
import UsersRoutes from "./users.js";

const router = express.Router();

// Mount each route under its path
router.use("/auth", AuthenticationRoutes);          // /api/auth/...
router.use("/bank-dashboard", BankDashboardRoutes); // /api/bank-dashboard/...
router.use("/farmer-profile", FarmerProfileRoutes);// /api/farmer-profile/...
router.use("/financial-history", FinancialHistoryRoutes); // /api/financial-history/...
router.use("/loan", LoanRoutes);                   // /api/loan/...
router.use("/transactions", TransactionRoutes);   // /api/transactions/...
router.use("/users", UsersRoutes);                // /api/users/...

export default router;
